# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db1e479a681f5d7a20af329d2f0808ffc578be73a16f49cd88916444cd6502409951d72439afccb657939858b95c3101cd6e71538d6cbcbd77d8c18dc1cfd507

test:
  secret_key_base: e5734f3e81e3731444f6b3f434a969bf7bcc47b4ecf6706b213d322ce2cc6899cc7250dc9d4d9565f7f2e8194180421d957ec59712c45231413cbdf29efb3e2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
